#!/usr/bin/env bash
# installs HAProxy load balancer
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup
cat<< EOF | sudo tee /etc/haproxy/haproxy.cfg >/dev/null
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout client 50000
        timeout connect 5000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend happyfaces-tech-frontend
        bind    *:80
        mode    http
        default_backend happyfaces-tech-backend

backend happyfaces-tech-backend
        balance roundrobin
        server 446460-web-01 54.165.3.212:80 check
        server 446460-web-02 100.24.235.18:80 check
EOF
sudo service haproxy restart
echo "HAProxy installed and configured successfully"
