#!/usr/bin/env bash
# installs HAProxy load balancer
sudo apt-get update -y
sudo apt-get install -y haproxy
cat<< EOF | sudo tee /etc/haproxy/haproxy.cfg >/dev/null
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
        bind *:80
        default_backend web_servers

backend web_servers
	mode http
        balance roundrobin
        server web-01 446460-web-01:80 54.165.3.212 check
        server web-02 446460-web-02:80 100.24.235.18 check
	http-response set-header X-Served-By %[src]
EOF
sudo service haproxy restart
echo "HAProxy installed and configured successfully"
