#!/usr/bin/env bash
# Finding out why the contaner's Nginx is not listening to the port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo kill "$(pgrep 'nginx' | head -1)"
