#!/usr/bin/env bash
# This script displays the content of non-hidden files in a list format
for file in *; do
	if [ -f "$file" ]; then
		name_after_dash=$(echo "$file" | cut -d'-' -f2-)
		echo "$name_after_dash"
	fi
done
