#!/usr/bin/env bash
# runs nginx as nginx
# Update Nginx configuration to run as nginx user
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
# Modify the default server block to listen on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
#Restart Nginx service
sudo -u nginx service nginx restart
